apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: development-

patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- name: image-registry.openshift-image-registry.svc:5000/restapi/development-restapi
  newName: image-registry.openshift-image-registry.svc:5000/restapi/development-restapi
  newTag: test07062022
- name: quay.io/dawid_jedrzejczak/restapi
  newName: quay.io/dawid_jedrzejczak/restapi
  newTag: latest
