apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: development-

patchesStrategicMerge:
- deployment.yaml
resources:
- ../../base
images:
- name: quay.io/dawid_jedrzejczak/restapi:latest