apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: restapi-ci
  namespace: restapi
spec:
  params:
    - default: >-
        quay.io/dawid_jedrzejczak/restapi
      name: IMAGE_NAME
      type: string
    - default: 'https://github.com/devopski/restapi.git'
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
    - default: latest
      name: IMAGE_TAG
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: restapi-workspace
    - name: build
      params:
        - name: IMAGE
          value: '$(params.IMAGE_NAME):$(params.IMAGE_TAG)'
        - name: TLSVERIFY
          value: 'false'
        - name: VERSION
          value: openjdk-17-ubi8
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-java
      workspaces:
        - name: source
          workspace: restapi-workspace
    - name: git-commit
      params:
        - name: GIT_REPOSITORY
          value: https://github.com/devopski/restapi-k8s.git
        - name: CURRENT_IMAGE
          value: $(params.IMAGE_NAME)
        - name: NEW_IMAGE
          value: '$(params.IMAGE_NAME):$(params.IMAGE_TAG)'
        - name: KUSTOMIZATION_PATH
          value: overlays/dev
      taskRef:
        kind: Task
        name: git-update-deployment
      runAfter:
        - build
      workspaces:
        - name: output
          workspace: restapi-workspace
  workspaces:
    - name: restapi-workspace
    
