apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: git
  name: create-release
  labels:
    app.kubernetes.io/version: '0.2'
    operator.tekton.dev/provider-type: community
spec:
  params:
    - name: release-name
      description: The tag of the release. There is a branch with release-$(release-name) available
    - name: old-image
    - name: new-image
    - name: tag
    - name: kustomize-dir
    - name: context-dir

  workspaces:
    - description: The workspace
      name: source

  results:
    - name: commit
      description: The commit SHA

  steps:
    - name: update-tag
      image: quay.io/wpernath/kustomize-ubi:latest
      workingDir: $(workspaces.source.path)/$(params.context-dir)/$(params.kustomize-dir)
      script: |        
        kustomize edit set image $(params.old-image)=$(params.new-image):$(params.tag)

        echo "##########################"
        echo "### kustomization.yaml ###"
        echo "##########################"
        cat kustomization.yaml

    - name: git-commit
      image: docker.io/alpine/git:v2.26.2
      workingDir: $(workspaces.source.path)/$(params.context-dir)
      script: |
        git config user.email "jedrzejczakdaw@gmail.com"
        git config user.name "Tekton Bot"

        git status
        git add $(params.kustomize-dir)/kustomization.yaml
        git commit -m "[ci] Branch for $(params.release-name) release"
        
        git push --set-upstream origin release-$(params.release-name)

        RESULT_SHA="$(git rev-parse HEAD | tr -d '\n')"
        EXIT_CODE="$?"
        if [ "$EXIT_CODE" != 0 ]
        then
          exit $EXIT_CODE
        fi
        # Make sure we don't add a trailing newline to the result!
        echo -n "$RESULT_SHA" > $(results.commit.path)