apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-manager # necessary for Kustomize identification
spec:
  replicas: 2
  template:
    spec:
      containers:
      - image: registry.gitlab.com/jedrzejczakdaw/aplikacja_kod:main46add4e1
        name: employee-manager # necessary for Kustomize identification
