apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restapi-pvc
  namespace: restapi
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
